dist: xenial
language: python
python:
  - "3.8.5"
services:
  - docker
install:
  - pip install tox neo4j-driver psycopg2 python-dotenv httpx
  - mkdir logs
  - mkdir cache
before_script:
  - export PYTHONPATH=$(pwd)
script:
  - tox
after_script:
  - docker-compose down