dist: xenial
language: python
python:
  - "3.7"
services:
  - docker
install:
  - pip install tox neo4j-driver psycopg2 python-dotenv httpx
  - mkdir logs
  - mkdir cache
before_script:
  - export PYTHONPATH=$(pwd)
  - ./tests/setup/startup_helpers.sh
script:
  - tox
after_script:
  - cd ./tests/helpers
  - docker-compose down