dist: xenial
language: python
python:
  - "3.8.5"
notifications:
  email:
    - powen@renci.org
services:
  - docker
install:
  - pip install -r ./tests/requirements.txt
  - pip install -r requirements.txt
  - mkdir logs
  - mkdir cache
before_script:
  - chmod 777 ./tests/setup/startup_helpers.sh
  - ./tests/setup/startup_helpers.sh
script:
  - tox
after_script:
  - cd ./tests/helpers
  - docker-compose down
