version: "3"
services:
  aragorn-ranker-compose:
    build:
      context: ./

    container_name: aragorn-ranker-deploy

    image: aragorn-ranker

    volumes:
      - ../logs:/d/dvols/logs
      - ./:/home/murphy/aragorn-ranker

    command: 'gunicorn --bind 0.0.0.0:4868 -w 4 -k uvicorn.workers.UvicornWorker -t 600 ranker.server:APP'

    ports:
      - 4868:4868

    stdin_open: true
    tty: true

