contact:
  title: ARAGORN Ranker
  email: bizon@renci.org
  name: Chris Bizon
  x-id: https://github.com/cbizon
  x-role: responsible developer
description: 'ARAGORN Ranker: The ranker used by the ARAGORN ARA, which takes a TRAPI 1.2 message containing answers, and calculates numerical scores for each answer.'
servers:
- description: Default server
  url: https://aragorn-ranker.renci.org
#- description: localhost
#  url: http://127.0.0.1/5003
termsOfService: http://robokop.renci.org:7055/tos?service_long=ARAGORN Ranker&provider_long=RENCI
title: ARAGORN Ranker
tags:
- name: translator
- name: ARAGORN
- name: ARA
x-translator:
  component: ARA
  team:
  - Ranking Agent
  infores: "infores:aragorn-ranker"
x-trapi:
  version: 1.2.0
  operations:
  - Rank by OmniCorp overlay
  - Rank by score
  - Rank by weight correctness