contact:
  email: patrick@covar.com
  name: Patrick Wang
  x-id: https://github.com/patrickkwang
  x-role: responsible developer
description: 'ARAGORN Ranker: The ranker used by the ARAGORN ARA, which takes a TRAPI 1.0 message containing answers, and calculates numerical scores for each answer.'
servers:
- description: Default server
  url: https://aragorn-ranker.renci.org
termsOfService: http://robokop.renci.org:7055/tos?service_long=ARAGORN Ranker&provider_long=RENCI
title: ARAGORN Ranker
tags:
- name: Translator
- name: ARAGORN
- name: ARA
x-translator:
  component: KP
  team:
  - Ranking Agent