###############
# test workflow for ARAGOR-Ranker
# powen, 9/15/2021
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        redis-version: [4]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create environment variables
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
          
      - name: Run the tests
        run: |
          python -m pytest tests/
