###############
# test workflow for ARAGOR-Ranker
# powen, 9/15/2021
###############

name: 'test'

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0]
        redis-version: [4]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create environment variables
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - name: Install app dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Startup helpers
        run: |
          bash tests/setup/startup_helpers.sh

      - name: Run the tests
        run: |
          python -m pytest tests/

      - name: Cleanup
        run: |
          bash tests/setup/shutdown_helpers.sh
